/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/my/my" |
       "/pages/home/home" |
       "/pages/about/about" |
       "/pages/base-info/base-info" |
       "/pages/detail/detail" |
       "/pages/favorite/favorite" |
       "/pages/login/login" |
       "/pages/login-code/login-code" |
       "/pages/news/news" |
       "/pages/protocols/protocols" |
       "/pages/recommendation/recommendation" |
       "/pages/search/search";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/home/home" | "/pages/news/news" | "/pages/my/my"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
